#服务配置
server:
  port: 9133
  max-http-header-size: 1024
  tomcat:
    max-threads: 800 #最大工作线程数量
    min-spare-threads: 20 #最小工作线程数量
    max-connections: 1000 #一瞬间最大支持的并发的连接数
    accept-count: 200 #等待队列长度
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
  application:
    name: newgrand-main-app
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:8067/ghc_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    #username: ghc
    #password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.6.111:3306/ghe_common_budget?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
#    username: root
#    password:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
#    typeAlis: org.clb.mybatisTest.entity
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200               #---ES的连接地址，多个地址用逗号分隔
      username:                          #---用户名
      password:                          #---密码
      connection-timeout: 1000           #---连接超时时间(默认1s)
      read-timeout: 1000                 #---读取超时时间(默认30s)
#mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: org.clb.mybatisTest.entity
mybatis:
#  mapper-locations: classpath:org.clb.mybatisTest.mapper/*:xml
  type-aliases-package: org.clb.mybatisTest.entity
  config-location: classpath:mybatis/mybatis-config.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org.clb.mybatisTest.mapper: DEBUG
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
