#服务配置
server:
  port: 9133
  max-http-header-size: 1024
spring:
  application:
    name: newgrand-main-app-cs-ydx
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:8067/ghc_dev?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    #username: ghc
    #password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password:
    typeAlis: rg.clb.mybatisTest.entity
#mybatis-plus:
#  config-location: classpath:mybatis/mybatis-config.xml
#  type-aliases-package: org.clb.mybatisTest.entity